### ISSUE TITLE
Send message to Telegram Topics

### ISSUE THREAD

**Issue by ciro-mota** [djmaze/apprise-microservice#9]
In Telegram, with the advent of groups divided into topics, it became possible to organize the sending of some reports through a bot.

In the documentation, you mention the example of caronc/apprise for configuring the apprise-microservice and [there it is already possible](https://github.com/caronc/apprise/issues/1143) to send messages to topics.

Is it possible to bring this functionality here? Or if it already exists here, how does it work? I tried to replicate the example there but the messages continue to be sent only directly to the bot, not to the topics.

My `yml` template:

```yml
services:
  shepherd:
    image: containrrr/shepherd
    environment:
      TZ: 'America/Bahia'
      VERBOSE: 'true'
      ROLLBACK_ON_FAILURE: 'true'
      APPRISE_SIDECAR_URL: notify:5000
      RUN_ONCE_AND_EXIT: 'true'
      IMAGE_AUTOCLEAN_LIMIT: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - shepherd_registry_password
    networks:
      - hlab-network
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=*/25 * * * *
        - swarm.cronjob.skip-running=true
      placement:
        constraints:
          - node.role == manager

  scheduler:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/Bahia
      - LOG_LEVEL=info
    deploy:
      placement:
        constraints:
          - node.role == manager

  notify:
    image: mazzolino/apprise-microservice:0.1
    networks:
      - hlab-network
    environment:
      NOTIFICATION_URLS: tgram://{bot_id}/{chat_id}/?topic=${message_thread_id}/?format=markdown
    deploy:
      placement:
        constraints:
          - node.role == manager

secrets:
  shepherd_registry_password:
    external: true

networks:
  hlab-network:
    external: true

```
